part of 'app_pages.dart';

abstract class Routes {
  Routes._();

  static const SPLASH = _Paths.SPLASH;
  static const ONBOARD_1 = _Paths.ONBOARD_1;
  static const ONBOARD_2 = _Paths.ONBOARD_2;
  static const ONBOARD_3 = _Paths.ONBOARD_3;
  static const WELCOME = _Paths.WELCOME;
  static const FORGOT_PASSWORD = _Paths.FORGOT_PASSWORD;
  static const ONBOARDING = _Paths.ONBOARDING;
  static const LOGIN = _Paths.LOGIN;
  static const REGISTER = _Paths.REGISTER;
  static const OTP_VERIFY = _Paths.OTP_VERIFY;
  static const EMAIL_VERIFY = _Paths.EMAIL_VERIFY;
  static const PROFILE_PHOTO_SIGNUP = _Paths.PROFILE_PHOTO_SIGNUP;
  static const SELFIE_VERIFY_SIGNUP = _Paths.SELFIE_VERIFY_SIGNUP;
  static const VERIFICATION_COMPLETE = _Paths.VERIFICATION_COMPLETE;
  static const ROLE_SELECTION = _Paths.ROLE_SELECTION;
  static const DRIVER_LICENSE = _Paths.DRIVER_LICENSE;
  static const DRIVER_RC = _Paths.DRIVER_RC;
  static const DRIVER_VEHICLE = _Paths.DRIVER_VEHICLE;
  static const DRIVER_REVIEW = _Paths.DRIVER_REVIEW;
  static const DRIVER_UNDER_REVIEW = _Paths.DRIVER_UNDER_REVIEW;
  static const DRIVER_APPROVED = _Paths.DRIVER_APPROVED;
  static const DRIVER_HOME = _Paths.DRIVER_HOME;
  static const HOME = _Paths.HOME;

  static const SEARCH_RIDES = _Paths.SEARCH_RIDES;
  static const RIDE_RESULTS = _Paths.RIDE_RESULTS;
  static const BOOKING = _Paths.BOOKING;
  static const MAKE_NEW_RIDE = _Paths.MAKE_NEW_RIDE;
  static const DATE_TIME = _Paths.DATE_TIME;
  static const MY_RIDES = _Paths.MY_RIDES;
  static const RIDE_DETAIL = _Paths.RIDE_DETAIL;
  static const LIVE_TRIP = _Paths.LIVE_TRIP;
  static const RATE_TRIP = _Paths.RATE_TRIP;
  static const CHAT_CAR_INFO = _Paths.CHAT_CAR_INFO;
  static const ORIGIN_SEARCH = _Paths.ORIGIN_SEARCH;
  static const MY_GARAGE = _Paths.MY_GARAGE;
  static const ACCOUNT = _Paths.ACCOUNT;
  static const SETTINGS = _Paths.SETTINGS;
  static const COUNTRIES = _Paths.COUNTRIES;
  static const EDIT_PROFILE = _Paths.EDIT_PROFILE;
  static const TRIP_HISTORY = _Paths.TRIP_HISTORY;
  static const PAYMENT_HISTORY = _Paths.PAYMENT_HISTORY;
  static const PROFILE_SETUP = _Paths.PROFILE_SETUP;
  static const PASSENGER_MODE = _Paths.PASSENGER_MODE;
  static const TRIP_PREFERENCES = _Paths.TRIP_PREFERENCES;
  static const TERMS = _Paths.TERMS;
  static const PRIVACY = _Paths.PRIVACY;
  static const RULES = _Paths.RULES;
  static const TRIPMATES_GALLERY = _Paths.TRIPMATES_GALLERY;
  static const IDENTITY_VERIFY = _Paths.IDENTITY_VERIFY;
  static const PAYMENTS_WALLET = _Paths.PAYMENTS_WALLET;
  static const DRIVER_IDENTITY_DETAILS = _Paths.DRIVER_IDENTITY_DETAILS;
  static const BANK_DETAILS = _Paths.BANK_DETAILS;
  static const DRIVER_WALLET = _Paths.DRIVER_WALLET;
  static const DRIVER_PAYOUT_HISTORY = _Paths.DRIVER_PAYOUT_HISTORY;
  static const DRIVER_EARNINGS_SUMMARY = _Paths.DRIVER_EARNINGS_SUMMARY;

  static const PASSENGER_SHELL = _Paths.PASSENGER_SHELL;
  static const PASSENGER_RIDE_RESULTS = _Paths.PASSENGER_RIDE_RESULTS;
  static const PASSENGER_RIDE_DETAIL = _Paths.PASSENGER_RIDE_DETAIL;
  static const PASSENGER_BOOK_RIDE = _Paths.PASSENGER_BOOK_RIDE;
  static const PASSENGER_BOOKING_CONFIRMED = _Paths.PASSENGER_BOOKING_CONFIRMED;
  static const PASSENGER_TRIP_PROGRESS = _Paths.PASSENGER_TRIP_PROGRESS;
  static const PASSENGER_SAFETY_SHARE = _Paths.PASSENGER_SAFETY_SHARE;
  static const PASSENGER_SAFETY_EMERGENCY = _Paths.PASSENGER_SAFETY_EMERGENCY;
  static const PASSENGER_SAFETY_SOS = _Paths.PASSENGER_SAFETY_SOS;
  static const PASSENGER_LIVE_TRACKING = _Paths.PASSENGER_LIVE_TRACKING;
  static const PASSENGER_TRIP_COMPLETED = _Paths.PASSENGER_TRIP_COMPLETED;
  static const PASSENGER_REVIEW_DRIVER = _Paths.PASSENGER_REVIEW_DRIVER;
  static const PASSENGER_PERSONAL_DETAILS = _Paths.PASSENGER_PERSONAL_DETAILS;
  static const PASSENGER_SUPPORT = _Paths.PASSENGER_SUPPORT;
}

abstract class _Paths {
  _Paths._();

  static const SPLASH = '/splash';
  static const ONBOARD_1 = '/onboard-1';
  static const ONBOARD_2 = '/onboard-2';
  static const ONBOARD_3 = '/onboard-3';
  static const WELCOME = '/welcome';
  static const FORGOT_PASSWORD = '/forgot-password';
  static const ONBOARDING = '/onboarding';
  static const LOGIN = '/login';
  static const REGISTER = '/register';
  static const OTP_VERIFY = '/otp-verify';
  static const EMAIL_VERIFY = '/email-verify';
  static const PROFILE_PHOTO_SIGNUP = '/profile-photo-signup';
  static const SELFIE_VERIFY_SIGNUP = '/selfie-verify-signup';
  static const VERIFICATION_COMPLETE = '/verification-complete';
  static const ROLE_SELECTION = '/role-selection';
  static const DRIVER_LICENSE = '/driver-onboarding/license';
  static const DRIVER_RC = '/driver-onboarding/rc';
  static const DRIVER_VEHICLE = '/driver-onboarding/vehicle';
  static const DRIVER_REVIEW = '/driver-onboarding/review';
  static const DRIVER_UNDER_REVIEW = '/driver-onboarding/under-review';
  static const DRIVER_APPROVED = '/driver-onboarding/approved';
  static const DRIVER_HOME = '/driver-home';
  static const HOME = '/home';

  static const SEARCH_RIDES = '/search-rides';
  static const RIDE_RESULTS = '/ride-results';
  static const BOOKING = '/booking';
  static const MAKE_NEW_RIDE = '/make-new-ride';
  static const DATE_TIME = '/date-time';
  static const MY_RIDES = '/my-rides';
  static const RIDE_DETAIL = '/ride-detail';
  static const LIVE_TRIP = '/live-trip';
  static const RATE_TRIP = '/rate-trip';
  static const CHAT_CAR_INFO = '/chat-car-info';
  static const ORIGIN_SEARCH = '/origin-search';
  static const MY_GARAGE = '/my-garage';
  static const ACCOUNT = '/account';
  static const SETTINGS = '/settings';
  static const COUNTRIES = '/countries';
  static const EDIT_PROFILE = '/edit-profile';
  static const TRIP_HISTORY = '/trip-history';
  static const PAYMENT_HISTORY = '/payment-history';
  static const PROFILE_SETUP = '/profile-setup';
  static const PASSENGER_MODE = '/passenger-mode';
  static const TRIP_PREFERENCES = '/trip-preferences';
  static const TRIPMATES_GALLERY = '/tripmates-gallery';
  static const TERMS = '/terms';
  static const PRIVACY = '/privacy';
  static const RULES = '/rules';
  static const IDENTITY_VERIFY = '/identity-verify';
  static const PAYMENTS_WALLET = '/payments-wallet';
  static const DRIVER_IDENTITY_DETAILS = '/driver-identity-details';
  static const BANK_DETAILS = '/bank-details';
  static const DRIVER_WALLET = '/driver-wallet';
  static const DRIVER_PAYOUT_HISTORY = '/driver-payout-history';
  static const DRIVER_EARNINGS_SUMMARY = '/driver-earnings-summary';

  static const PASSENGER_SHELL = '/passenger-shell';
  static const PASSENGER_RIDE_RESULTS = '/passenger/ride-results';
  static const PASSENGER_RIDE_DETAIL = '/passenger/ride-detail';
  static const PASSENGER_BOOK_RIDE = '/passenger/book-ride';
  static const PASSENGER_BOOKING_CONFIRMED = '/passenger/booking-confirmed';
  static const PASSENGER_TRIP_PROGRESS = '/passenger/trip-progress';
  static const PASSENGER_SAFETY_SHARE = '/passenger/safety/share-location';
  static const PASSENGER_SAFETY_EMERGENCY = '/passenger/safety/emergency';
  static const PASSENGER_SAFETY_SOS = '/passenger/safety/sos';
  static const PASSENGER_LIVE_TRACKING = '/passenger/live-tracking';
  static const PASSENGER_TRIP_COMPLETED = '/passenger/trip-completed';
  static const PASSENGER_REVIEW_DRIVER = '/passenger/review-driver';
  static const PASSENGER_PERSONAL_DETAILS = '/passenger/personal-details';
  static const PASSENGER_SUPPORT = '/passenger/support';
}
